/*
 * This source file was generated by the Gradle 'init' task
 */
package com.miempresa.ejercicios;

import java.util.Scanner;

public class holaMundo {
      public static void main (String [] args) {
        System.out.println("¡Hola Mundo!"); //Imprimir un Hola Mundo
        
        //Declarar variables y darles valor
        int kilos = 55;
        String nombre = "pepe";
        boolean bueno = true;
        char puerta = 'a';
        float dinero = (float) 12.32;
        double litros = 25.689;
                
        //Menú switch para elegir entre operaciones distintas
        int intro;
        Scanner escribe;
        escribe = new Scanner(System.in);
        do {
            System.out.println("Introduce el número de la operación que desees hacer:\n 1 para suma.\n 2 para resta.\n 3 para conocer el área de un círculo dando su rádio.\n 4 para cambiar los valores de dos variables.\n 5 para saber si un número es par o no.\n 6 para ver por pantalla los números del 1 al 10.\n 7 para sumar todos los números del 1 al 100.\n Pulsa 0 para salir.");
            intro = escribe.nextInt();
            switch (intro){
                case 1:
                    sumar();
                    break;
                case 2:
                    restar();
                    break;
                case 3:
                    radiar();
                    break;
                case 4:
                    cambio();
                    break;
                case 5:
                    par();
                    break;
                case 6:
                    diez();
                    break;
                case 7:
                    cien();
                    break;
                case 0:
                    System.out.println("Saliste del programa.");
                    break;
                default:
                    System.out.println("Operación no encontrada.\nPor favor, marque un número que corresponda a una operación.");
                    break;
                }
        }
        while (intro!=0);
    } 
    
    //1. Método suma
    public static void sumar(){
        int sum1;
        int sum2;
        int total1;
        
        Scanner leer;
        leer = new Scanner(System.in);
        System.out.println("Escribe un número para sumar");
        sum1 = leer.nextInt();
        System.out.println("Escribe el segundo número para sumar");
        sum2 = leer.nextInt();
        
        total1 = sum1+sum2;
        System.out.println("La suma de "+sum1+" y "+sum2+" es: "+total1);
        
    } 
    
    //2. Método resta
    public static void restar(){
        int res1;
        int res2;
        int total2;
        
        Scanner leer;
        leer = new Scanner(System.in);
        System.out.println("Escribe un número para restar");
        res1 = leer.nextInt();
        System.out.println("Escribe un número para restarle al anterior");
        res2 = leer.nextInt();
        
        total2 = res1-res2;
        System.out.println("El resultado de restarle a "+res1+" el valor "+res2+" es: "+total2);
    }
    
    //3. Calcula el área de un círculo conociendo su rádio
    public static void radiar(){
        double radio;
        double area;
        
        Scanner leer;
        leer = new Scanner (System.in);
        System.out.println("Escribe el radio del círculo del que quieras conocer su área");
        radio = leer.nextInt();
        
        area = Math.PI * radio * radio;
        System.out.println("El área del círculo de radio "+radio+" es: "+area);
    }
   
    //4. Método que intercambia los valores de 2 variables
    public static void cambio(){
        int uno;
        int dos;
        int auxiliar;
        
        Scanner leer;
        leer = new Scanner (System.in);
        System.out.println("Escribe la variable uno");
        uno = leer.nextInt();
        System.out.println("Escribe la segunda variable");
        dos = leer.nextInt();
        
        auxiliar = uno;
        uno = dos;
        dos = auxiliar;
        System.out.println("El valor final de uno es: "+uno+" y el valor final de dos es: "+dos);
    }
    
    //5. Método que diferencia par de impar
    public static void par(){
        int num;
        int resto;
        String resul;
        Scanner leer;
        
        leer = new Scanner(System.in);
        System.out.println("Introduce un número para saber si es par o impar");
        num = leer.nextInt();
        
        resto = num%2;
        if (resto!=0){
            resul = "es impar";
            
        } else {
            resul = "es par";
        }
        System.out.println(num+" "+resul);
    }
    
    //6. Imprime los números del 1 al 10
    public static void diez(){
        for (int i = 1; i <= 10; i++){
            System.out.println(i);
        }
    }
    
    //7. Suma los números del 1 al 100
    public static void cien(){
        int total100 = 0;
        
        for (int i = 1; i <= 100; i++){
            total100=total100+i;
        }
        System.out.println("La suma de todos los números del 1 al 100 es; "+total100);
    }
}
