/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.zaltor.gui;

import com.zaltor.juegoRol.*;

/**
 * Clase para la elección de personaje.
 * @author mss7
 */
public class VentanaEleccionPersonaje extends javax.swing.JDialog {

    /**
     * Creates new form VentanaEleccionPersonaje
     */
    public VentanaEleccionPersonaje(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private String personajeSeleccionado;
    /**
     * 
     * @return Devuelve el personaje seleccionado
     */
    public String getPersonajeSeleccionado() {
        return personajeSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jbGuerrera = new javax.swing.JButton();
        jbChaman = new javax.swing.JButton();
        jbNinja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlTitulo.setText("¿Qué personaje quieres ser?");

        jbGuerrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbGuerrera.setText("Guerrera");
        jbGuerrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuerreraActionPerformed(evt);
            }
        });

        jbChaman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbChaman.setText("Chamán");
        jbChaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChamanActionPerformed(evt);
            }
        });

        jbNinja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbNinja.setText("Ninja");
        jbNinja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNinjaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guerrera_re_267x400.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chaman_re_267x400.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ninja_re_267x400.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jbGuerrera)
                        .addGap(270, 270, 270)
                        .addComponent(jbChaman))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jlTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jbNinja)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlTitulo)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbChaman)
                    .addComponent(jbGuerrera)
                    .addComponent(jbNinja))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Si pulsas Guerrera, devuelve ese personaje ycierra la ventana.
     * @param evt 
     */
    private void jbGuerreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuerreraActionPerformed
        personajeSeleccionado = "Guerrera";
        dispose();

    }//GEN-LAST:event_jbGuerreraActionPerformed
    
    /**
     * Hace lo mismo para Chaman.
     * @param evt 
     */
    private void jbChamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChamanActionPerformed
        personajeSeleccionado = "Chaman";
        dispose();
    }//GEN-LAST:event_jbChamanActionPerformed
    
    /**
     * Y para Ninja
     * @param evt 
     */
    private void jbNinjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNinjaActionPerformed
        personajeSeleccionado = "Ninja";
        dispose();
    }//GEN-LAST:event_jbNinjaActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbChaman;
    private javax.swing.JButton jbGuerrera;
    private javax.swing.JButton jbNinja;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
