/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.zaltor.gui;

import com.zaltor.juegoRol.*;

/**
 * Clase para ver las estadísticas de los personajes.
 *
 * @author mss7
 */
public class VentanaEstadisticas extends javax.swing.JDialog {

    public Guerrero g = new Guerrero("Guerrera");
    public Chaman c = new Chaman("Chaman");
    public Ninja n = new Ninja("Ninja");

    /**
     * Creates new form VentanaEstadisticas
     */
    public VentanaEstadisticas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbTitulo = new javax.swing.JLabel();
        jbGuerrera = new javax.swing.JButton();
        jbChaman = new javax.swing.JButton();
        jbNinja = new javax.swing.JButton();
        jtEstadisticas = new javax.swing.JTextArea();
        jbOk = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbTitulo.setText("Pulsa el nombre del personaje para ver sus estadísticas");

        jbGuerrera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbGuerrera.setText("Guerrera");
        jbGuerrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuerreraActionPerformed(evt);
            }
        });

        jbChaman.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbChaman.setText("Chamán");
        jbChaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChamanActionPerformed(evt);
            }
        });

        jbNinja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbNinja.setText("Ninja");
        jbNinja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNinjaActionPerformed(evt);
            }
        });

        jtEstadisticas.setEditable(false);
        jtEstadisticas.setColumns(20);
        jtEstadisticas.setRows(1);

        jbOk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbOk.setText("Continuar");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbGuerrera)
                                .addGap(112, 112, 112)
                                .addComponent(jbChaman)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbNinja))
                            .addComponent(jbTitulo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jbLimpiar)
                        .addGap(128, 128, 128)
                        .addComponent(jbOk))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jtEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jbTitulo)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNinja)
                    .addComponent(jbChaman)
                    .addComponent(jbGuerrera))
                .addGap(26, 26, 26)
                .addComponent(jtEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiar)
                    .addComponent(jbOk))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpia el recuadro de texto.
     *
     * @param evt
     */
    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        jtEstadisticas.setText("");
    }//GEN-LAST:event_jbLimpiarActionPerformed

    /**
     * Cierra la ventana.
     *
     * @param evt
     */
    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        dispose();
    }//GEN-LAST:event_jbOkActionPerformed

    /**
     * Para ver las estadísticas de Ninja.
     *
     * @param evt
     */
    private void jbNinjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNinjaActionPerformed
        jtEstadisticas.setText(n.mostrarInfo());
    }//GEN-LAST:event_jbNinjaActionPerformed

    /**
     * Para las estadísticas de Chaman.
     *
     * @param evt
     */
    private void jbChamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChamanActionPerformed
        jtEstadisticas.setText(c.mostrarInfo());
    }//GEN-LAST:event_jbChamanActionPerformed

    /**
     * Muestra estadísticas d eGuerrera.
     *
     * @param evt
     */
    private void jbGuerreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuerreraActionPerformed
        jtEstadisticas.setText(g.mostrarInfo());
    }//GEN-LAST:event_jbGuerreraActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbChaman;
    private javax.swing.JButton jbGuerrera;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbNinja;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jbTitulo;
    private javax.swing.JTextArea jtEstadisticas;
    // End of variables declaration//GEN-END:variables
}
